# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' movmean
#'
#' NA and Inf values in the xx will be ignored automatically.
#'
#' @param x A numeric vector.
#' @param halfwin Integer, half of moving window size
#' @param w Corresponding weights of xx, same long as yy.
#'
#' @examples
#' x <- 1:100
#' x[50] <- NA; x[80] <- Inf
#' s1 <- movmean_rcpp(x, 1)
#' s2 <- movmean_rcpp(x, 2)
#' @export
movmean_rcpp <- function(x, halfwin = 1L, w = NULL) {
    .Call(`_movmean_movmean_rcpp`, x, halfwin, w)
}

multiply_f90 <- function(x, y) {
    .Call(`_movmean_multiply_f90`, x, y)
}

