# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' movmean
#'
#' NA and Inf values in the yy will be ignored automatically.
#'
#' @param y A numeric vector.
#' @param halfwin Integer, half of moving window size
#' @param w Corresponding weights of yy, same long as yy.
#' 
#' @examples
#' x <- 1:100
#' x[50] <- NA; x[80] <- Inf
#' s1 <- movmean(x, 1)
#' s2 <- movmean(x, 2)
#' @export
movmean <- function(y, halfwin = 1L, w = NULL) {
    .Call(`_movmean_movmean`, y, halfwin, w)
}

multiply_f90 <- function(x, y) {
    .Call(`_movmean_multiply_f90`, x, y)
}

